name: Create Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup jdk 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew chiseledBuild

      - name: Publish-1.20.1-Fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 906926
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          name: v${{github.ref_name}} for Fabric 1.20.1
          files: 'versions/1.20.1-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'

      - name: Publish-1.20.1-Fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: Pf8PJBb5
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          name: v${{github.ref_name}} for Fabric 1.20.1
          files: 'versions/1.20.1-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'

      - name: Publish-1.20.2-Fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 906926
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          name: v${{github.ref_name}} for Fabric 1.20.2
          files: 'versions/1.20.2-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'

      - name: Publish-1.20.2-Fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: Pf8PJBb5
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          name: v${{github.ref_name}} for Fabric 1.20.2
          files: 'versions/1.20.2-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'

      - name: Publish-1.20.4-Fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 906926
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          name: v${{github.ref_name}} for Fabric 1.20.4
          files: 'versions/1.20.4-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'

      - name: Publish-1.20.4-Fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: Pf8PJBb5
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          name: v${{github.ref_name}} for Fabric 1.20.4
          files: 'versions/1.20.4-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'

      - name: Publish-1.20.6-Fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 906926
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          name: v${{github.ref_name}} for Fabric 1.20.6
          files: 'versions/1.20.6-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'

      - name: Publish-1.20.6-Fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: Pf8PJBb5
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          name: v${{github.ref_name}} for Fabric 1.20.6
          files: 'versions/1.20.6-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'

      - name: Publish-1.21.1-Fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 906926
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          name: v${{github.ref_name}} for Fabric 1.21.1
          files: 'versions/1.21.1-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'

      - name: Publish-1.21.1-Fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: Pf8PJBb5
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          name: v${{github.ref_name}} for Fabric 1.21.1
          files: 'versions/1.21.1-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
